/**
 * THỨ TỰ HIỂN THỊ CÂU HỎI — sinh bởi `scripts/sinh-thu-tu.mjs`, ĐỪNG SỬA TAY.
 *
 * Sinh lại sau mỗi lần đổi ngân hàng câu: `node scripts/sinh-thu-tu.mjs`
 *
 * 🔴 Thứ tự này CHỐT CỨNG có chủ đích. Trộn lúc chạy thì hai lần làm bài ra hai thứ tự
 * khác nhau ⇒ mất khả năng đối chiếu con ↔ cha mẹ, và mất khả năng tái hiện lỗi.
 *
 * Luật sinh (DISC_BA.md §6.6): vòng 4 câu đủ D–I–S–C · thứ tự trục xoay qua từng vòng ·
 * hai câu đảo không đứng cạnh nhau, mỗi câu đảo một vòng · câu đầu bài luôn là câu thuận.
 */

import type { MaBoDe } from "@modules/core/bo-de/kieu";

export const THU_TU: Readonly<Record<MaBoDe, readonly string[]>> = {
  MN: [
    "MN-D1",
    "MN-I5",
    "MN-S1",
    "MN-C1",
    "MN-I1",
    "MN-S2",
    "MN-C2",
    "MN-D5",
    "MN-S3",
    "MN-C5",
    "MN-D2",
    "MN-I2",
    "MN-C3",
    "MN-D3",
    "MN-I3",
    "MN-S5",
    "MN-D4",
    "MN-S4",
    "MN-I4",
    "MN-C4",
  ],
  TH: [
    "TH-D1",
    "TH-I5",
    "TH-S1",
    "TH-C1",
    "TH-I1",
    "TH-S2",
    "TH-C2",
    "TH-D5",
    "TH-S3",
    "TH-C5",
    "TH-D2",
    "TH-I2",
    "TH-C3",
    "TH-D3",
    "TH-I3",
    "TH-S5",
    "TH-D4",
    "TH-S4",
    "TH-I4",
    "TH-C4",
  ],
  THCS: [
    "THCS-D1",
    "THCS-I6",
    "THCS-S1",
    "THCS-C1",
    "THCS-I1",
    "THCS-S2",
    "THCS-C2",
    "THCS-D6",
    "THCS-S3",
    "THCS-C6",
    "THCS-D2",
    "THCS-I2",
    "THCS-C3",
    "THCS-D3",
    "THCS-I3",
    "THCS-S6",
    "THCS-D4",
    "THCS-S4",
    "THCS-I4",
    "THCS-C4",
    "THCS-S5",
    "THCS-I5",
    "THCS-C5",
    "THCS-D5",
  ],
  PH: [
    "PH-D1",
    "PH-I6",
    "PH-S1",
    "PH-C1",
    "PH-I1",
    "PH-S2",
    "PH-C2",
    "PH-D6",
    "PH-S3",
    "PH-C6",
    "PH-D2",
    "PH-I2",
    "PH-C3",
    "PH-D3",
    "PH-I3",
    "PH-S6",
    "PH-D4",
    "PH-S4",
    "PH-I4",
    "PH-C4",
    "PH-S5",
    "PH-I5",
    "PH-C5",
    "PH-D5",
  ],
  QS: [
    "QS-D1",
    "QS-I4",
    "QS-S1",
    "QS-C1",
    "QS-I1",
    "QS-S2",
    "QS-C2",
    "QS-D4",
    "QS-S3",
    "QS-C4",
    "QS-D2",
    "QS-I2",
    "QS-C3",
    "QS-D3",
    "QS-I3",
    "QS-S4",
  ],
};
