/**
 * NGÂN HÀNG CÂU HỎI DISC — 104 câu, 5 bộ đề.
 *
 * 🔴 NGUỒN NỘI DUNG: `docs/BA/DISC_BA.md` mục 6. Bộ câu do SATA ROBO biên soạn theo
 * mô hình DISC. KHÔNG dịch bộ từ của bên bán, KHÔNG tuyên bố "chuẩn quốc tế" — chưa có
 * bộ dữ liệu chuẩn hoá trên người Việt thì lời hứa đó là một cái nút dối (DISC_BA.md §3.3).
 *
 * 🔴 LUẬT KHI SỬA NỘI DUNG:
 *  1. Mỗi trục phải giữ ÍT NHẤT MỘT câu đảo chiều. Gỡ câu đảo cuối cùng của một trục là
 *     gỡ hàng rào chống tick-một-cột — lỗi IM LẶNG, bài vẫn chạy, chỉ sai kết quả.
 *     `tests/cau-hoi.test.ts` canh việc này. Đừng gỡ test đó.
 *  2. Sửa/thêm/bớt câu ⇒ TĂNG `PHIEN_BAN_BO_DE` rồi chạy lại `node scripts/sinh-checksum.mjs`.
 *     Không tăng thì `npm run kiem` sẽ đỏ — cố ý.
 *  3. Sửa xong phải chạy lại `node scripts/sinh-thu-tu.mjs`.
 *
 * ⚠️ File này đi thẳng ra bundle công khai. KHÔNG đặt họ tên, tên cơ sở, số điện thoại vào đây.
 *
 * ⚠️ BỐN CHỖ DO MÁY SOẠN, KHÔNG CÓ TRONG BA DOC — người duyệt nội dung xem kỹ:
 *    · nhãn 3 mức giữa của thang bộ PH và bộ QS (BA doc chỉ cho hai đầu mút)
 *    · câu dẫn của bộ THCS, PH, QS (BA doc chỉ cho câu dẫn của MN và TH)
 */

import type { NganHang } from "@modules/core/bo-de/kieu";

/** Tăng số này mỗi khi sửa nội dung câu. Xem luật 2 ở đầu file. */
export const PHIEN_BAN_BO_DE = "1.1";

export const NGAN_HANG: NganHang = {
  MN: {
    ma: "MN",
    ten: "Mầm non",
    aiTraLoi: "Phụ huynh hoặc giáo viên",
    veAi: "Bé 3–7 tuổi",
    loaiThang: "tan-suat",
    mucToiDa: 5,
    cauMoiMan: 5,
    cauDan: "Nghĩ về hai tuần gần đây. Bé thường…",
    thang: [
      { giaTri: 1, nhan: "Hầu như không" },
      { giaTri: 2, nhan: "Hiếm khi" },
      { giaTri: 3, nhan: "Thỉnh thoảng" },
      { giaTri: 4, nhan: "Thường xuyên" },
      { giaTri: 5, nhan: "Hầu như luôn" },
    ],
    cau: [
      { ma: "MN-D1", truc: "D", dao: false,
        noiDung: "Tự chọn trò chơi rồi rủ bạn chơi theo cách của mình" },
      { ma: "MN-D2", truc: "D", dao: false,
        noiDung: "Đòi tự làm, không muốn người lớn làm giúp" },
      { ma: "MN-D3", truc: "D", dao: false,
        noiDung: "Phản ứng ngay khi bị lấy mất đồ chơi" },
      { ma: "MN-D4", truc: "D", dao: false,
        noiDung: "Không ngại thử trò chơi mới mà bé chưa biết" },
      { ma: "MN-D5", truc: "D", dao: true,
        noiDung: "Chờ người lớn bảo mới bắt đầu làm" },
      { ma: "MN-I1", truc: "I", dao: false,
        noiDung: "Kể lại chuyện ở lớp ngay khi về đến nhà" },
      { ma: "MN-I2", truc: "I", dao: false,
        noiDung: "Bắt chuyện với người lạ mà không nép" },
      { ma: "MN-I3", truc: "I", dao: false,
        noiDung: "Thích hát, múa, diễn trước mọi người" },
      { ma: "MN-I4", truc: "I", dao: false,
        noiDung: "Nét mặt và cử chỉ rất phong phú khi nói" },
      { ma: "MN-I5", truc: "I", dao: true,
        noiDung: "Chơi một mình rất lâu mà không cần bạn" },
      { ma: "MN-S1", truc: "S", dao: false,
        noiDung: "Nhường đồ chơi cho bạn" },
      { ma: "MN-S2", truc: "S", dao: false,
        noiDung: "Cần biết trước sắp làm gì thì mới yên tâm" },
      { ma: "MN-S3", truc: "S", dao: false,
        noiDung: "An ủi khi thấy bạn hoặc người nhà buồn" },
      { ma: "MN-S4", truc: "S", dao: false,
        noiDung: "Giữ một thói quen (ăn, ngủ, cất đồ) rất đều" },
      { ma: "MN-S5", truc: "S", dao: true,
        noiDung: "Thích đổi chỗ, đổi trò, đổi việc liên tục" },
      { ma: "MN-C1", truc: "C", dao: false,
        noiDung: "Để ý và nhắc khi có gì đặt sai chỗ" },
      { ma: "MN-C2", truc: "C", dao: false,
        noiDung: "Làm theo đúng thứ tự người lớn dặn" },
      { ma: "MN-C3", truc: "C", dao: false,
        noiDung: "Ngồi lâu với một việc cần tỉ mỉ (xếp hình, tô màu)" },
      { ma: "MN-C4", truc: "C", dao: false,
        noiDung: "Hỏi \"vì sao\" rất nhiều" },
      { ma: "MN-C5", truc: "C", dao: true,
        noiDung: "Làm cho xong rồi bỏ đó, không quan tâm gọn hay không" },
    ],
  },
  TH: {
    ma: "TH",
    ten: "Tiểu học",
    aiTraLoi: "Học sinh lớp 3–5",
    veAi: "Chính mình",
    loaiThang: "dong-y",
    mucToiDa: 3,
    cauMoiMan: 5,
    cauDan: "Đọc từng câu và chọn cái giống em nhất. Không có câu nào đúng hay sai cả.",
    thang: [
      { giaTri: 1, nhan: "Không phải", mat: "🙁" },
      { giaTri: 2, nhan: "Đôi khi", mat: "😐" },
      { giaTri: 3, nhan: "Đúng rồi", mat: "😀" },
    ],
    cau: [
      { ma: "TH-D1", truc: "D", dao: false,
        noiDung: "Khi chơi trò mới, em thường là người bày cách chơi" },
      { ma: "TH-D2", truc: "D", dao: false,
        noiDung: "Em xung phong lên bảng" },
      { ma: "TH-D3", truc: "D", dao: false,
        noiDung: "Em nói ra khi thấy bạn làm chưa đúng" },
      { ma: "TH-D4", truc: "D", dao: false,
        noiDung: "Em thích thi xem ai nhanh hơn" },
      { ma: "TH-D5", truc: "D", dao: true,
        noiDung: "Trong nhóm, em thường để bạn khác chọn giúp" },
      { ma: "TH-I1", truc: "I", dao: false,
        noiDung: "Em thích kể chuyện cho các bạn nghe" },
      { ma: "TH-I2", truc: "I", dao: false,
        noiDung: "Em làm quen với bạn mới rất nhanh" },
      { ma: "TH-I3", truc: "I", dao: false,
        noiDung: "Em thích được cô khen trước lớp" },
      { ma: "TH-I4", truc: "I", dao: false,
        noiDung: "Em hay pha trò cho các bạn cười" },
      { ma: "TH-I5", truc: "I", dao: true,
        noiDung: "Em thích chơi một mình hơn chơi với nhóm đông" },
      { ma: "TH-S1", truc: "S", dao: false,
        noiDung: "Em chờ đến lượt mình mà không sốt ruột" },
      { ma: "TH-S2", truc: "S", dao: false,
        noiDung: "Em cho bạn mượn đồ của em" },
      { ma: "TH-S3", truc: "S", dao: false,
        noiDung: "Em thấy vui khi mọi việc giống hôm qua" },
      { ma: "TH-S4", truc: "S", dao: false,
        noiDung: "Em dỗ bạn khi bạn khóc" },
      { ma: "TH-S5", truc: "S", dao: true,
        noiDung: "Đổi chỗ ngồi hay đổi lịch học không làm em thấy khó chịu" },
      { ma: "TH-C1", truc: "C", dao: false,
        noiDung: "Em xếp đồ của em theo đúng chỗ" },
      { ma: "TH-C2", truc: "C", dao: false,
        noiDung: "Em soát lại bài trước khi nộp" },
      { ma: "TH-C3", truc: "C", dao: false,
        noiDung: "Em làm đúng như cô dặn" },
      { ma: "TH-C4", truc: "C", dao: false,
        noiDung: "Em hỏi lại cho rõ trước khi làm" },
      { ma: "TH-C5", truc: "C", dao: true,
        noiDung: "Em làm nhanh cho xong, sai chỗ nào sửa sau" },
    ],
  },
  THCS: {
    ma: "THCS",
    ten: "Trung học cơ sở",
    aiTraLoi: "Học sinh lớp 6–9",
    veAi: "Chính mình",
    loaiThang: "dong-y",
    mucToiDa: 5,
    cauMoiMan: 5,
    cauDan: "Chọn mức giống mình nhất. Không có câu nào đúng hay sai.",
    thang: [
      { giaTri: 1, nhan: "Rất không giống mình" },
      { giaTri: 2, nhan: "Không giống lắm" },
      { giaTri: 3, nhan: "Nửa nọ nửa kia" },
      { giaTri: 4, nhan: "Khá giống mình" },
      { giaTri: 5, nhan: "Rất giống mình" },
    ],
    cau: [
      { ma: "THCS-D1", truc: "D", dao: false,
        noiDung: "Khi cả nhóm còn đang bàn, mình là người nói \"thôi cứ làm cách này đi\"" },
      { ma: "THCS-D2", truc: "D", dao: false,
        noiDung: "Mình xung phong nhận phần khó nhất của bài nhóm" },
      { ma: "THCS-D3", truc: "D", dao: false,
        noiDung: "Mình nói thẳng khi thấy bạn làm sai, dù bạn có thể phật lòng" },
      { ma: "THCS-D4", truc: "D", dao: false,
        noiDung: "Mình thích những việc có thắng thua rõ ràng" },
      { ma: "THCS-D5", truc: "D", dao: false,
        noiDung: "Bị phản đối không làm mình bỏ ý kiến của mình" },
      { ma: "THCS-D6", truc: "D", dao: true,
        noiDung: "Trong nhóm, mình thường để bạn khác quyết rồi làm theo" },
      { ma: "THCS-I1", truc: "I", dao: false,
        noiDung: "Mình bắt chuyện được với bạn mới mà không thấy ngại" },
      { ma: "THCS-I2", truc: "I", dao: false,
        noiDung: "Mình thuyết phục bạn bằng cách kể chuyện hơn là đưa số liệu" },
      { ma: "THCS-I3", truc: "I", dao: false,
        noiDung: "Mình thích đứng trước lớp trình bày" },
      { ma: "THCS-I4", truc: "I", dao: false,
        noiDung: "Bạn bè hay tìm mình khi muốn rủ đi đâu đó" },
      { ma: "THCS-I5", truc: "I", dao: false,
        noiDung: "Mình dễ làm không khí nhóm vui lên" },
      { ma: "THCS-I6", truc: "I", dao: true,
        noiDung: "Mình thấy mệt sau khi ở chỗ đông người" },
      { ma: "THCS-S1", truc: "S", dao: false,
        noiDung: "Mình làm xong việc đang dở rồi mới bắt việc mới" },
      { ma: "THCS-S2", truc: "S", dao: false,
        noiDung: "Bạn bè hay kể chuyện buồn cho mình nghe" },
      { ma: "THCS-S3", truc: "S", dao: false,
        noiDung: "Mình nhường phần mình thích để nhóm khỏi tranh cãi" },
      { ma: "THCS-S4", truc: "S", dao: false,
        noiDung: "Mình thấy yên tâm khi biết trước hôm nay sẽ làm gì" },
      { ma: "THCS-S5", truc: "S", dao: false,
        noiDung: "Mình chờ được lâu mà không sốt ruột" },
      { ma: "THCS-S6", truc: "S", dao: true,
        noiDung: "Lịch sinh hoạt cứ lặp lại mãi một kiểu làm mình thấy bí bách" },
      { ma: "THCS-C1", truc: "C", dao: false,
        noiDung: "Mình dò lại bài một lượt nữa dù đã làm xong" },
      { ma: "THCS-C2", truc: "C", dao: false,
        noiDung: "Mình đọc kỹ hướng dẫn trước khi bắt tay vào làm" },
      { ma: "THCS-C3", truc: "C", dao: false,
        noiDung: "Mình khó chịu khi việc làm ẩu mà vẫn được cho qua" },
      { ma: "THCS-C4", truc: "C", dao: false,
        noiDung: "Mình hay hỏi lại \"vì sao lại làm thế\" trước khi đồng ý" },
      { ma: "THCS-C5", truc: "C", dao: false,
        noiDung: "Mình ghi chép lại để khỏi quên" },
      { ma: "THCS-C6", truc: "C", dao: true,
        noiDung: "Mình bắt tay vào làm trước rồi tính sau" },
    ],
  },
  PH: {
    ma: "PH",
    ten: "Phụ huynh",
    aiTraLoi: "Phụ huynh",
    veAi: "Chính mình",
    loaiThang: "dong-y",
    mucToiDa: 5,
    cauMoiMan: 5,
    cauDan: "Chọn mức đúng với bạn nhất. Không có câu nào đúng hay sai.",
    thang: [
      { giaTri: 1, nhan: "Rất không đúng với tôi" },
      { giaTri: 2, nhan: "Không đúng lắm" },
      { giaTri: 3, nhan: "Nửa nọ nửa kia" },
      { giaTri: 4, nhan: "Khá đúng với tôi" },
      { giaTri: 5, nhan: "Rất đúng với tôi" },
    ],
    cau: [
      { ma: "PH-D1", truc: "D", dao: false,
        noiDung: "Trong nhà, tôi là người ra quyết định cuối cùng" },
      { ma: "PH-D2", truc: "D", dao: false,
        noiDung: "Tôi nói thẳng vấn đề thay vì vòng vo" },
      { ma: "PH-D3", truc: "D", dao: false,
        noiDung: "Khi có việc gấp, tôi làm luôn chứ không đợi bàn thêm" },
      { ma: "PH-D4", truc: "D", dao: false,
        noiDung: "Tôi đặt mục tiêu cao cho bản thân và cho con" },
      { ma: "PH-D5", truc: "D", dao: false,
        noiDung: "Tôi giữ lập trường ngay cả khi bị phản đối" },
      { ma: "PH-D6", truc: "D", dao: true,
        noiDung: "Tôi thường để người khác quyết cho nhanh việc" },
      { ma: "PH-I1", truc: "I", dao: false,
        noiDung: "Tôi dễ bắt chuyện với phụ huynh khác" },
      { ma: "PH-I2", truc: "I", dao: false,
        noiDung: "Tôi thuyết phục con bằng cách kể chuyện hơn là ra lệnh" },
      { ma: "PH-I3", truc: "I", dao: false,
        noiDung: "Người khác nói tôi là người vui vẻ, dễ gần" },
      { ma: "PH-I4", truc: "I", dao: false,
        noiDung: "Tôi thích tham gia hoạt động tập thể của lớp con" },
      { ma: "PH-I5", truc: "I", dao: false,
        noiDung: "Tôi hay động viên, khen ngợi thành tiếng" },
      { ma: "PH-I6", truc: "I", dao: true,
        noiDung: "Tôi ngại nói trước đông người" },
      { ma: "PH-S1", truc: "S", dao: false,
        noiDung: "Tôi giữ nếp sinh hoạt gia đình đều đặn" },
      { ma: "PH-S2", truc: "S", dao: false,
        noiDung: "Tôi nhường để nhà cửa êm ấm" },
      { ma: "PH-S3", truc: "S", dao: false,
        noiDung: "Tôi kiên nhẫn nghe con nói hết" },
      { ma: "PH-S4", truc: "S", dao: false,
        noiDung: "Tôi cần thời gian để quen với thay đổi lớn" },
      { ma: "PH-S5", truc: "S", dao: false,
        noiDung: "Người thân hay tìm tôi để tâm sự" },
      { ma: "PH-S6", truc: "S", dao: true,
        noiDung: "Tôi thích xáo trộn, thay đổi cho mới mẻ" },
      { ma: "PH-C1", truc: "C", dao: false,
        noiDung: "Tôi tìm hiểu kỹ trước khi chọn lớp học cho con" },
      { ma: "PH-C2", truc: "C", dao: false,
        noiDung: "Tôi giữ giấy tờ, hoá đơn, sổ sách ngăn nắp" },
      { ma: "PH-C3", truc: "C", dao: false,
        noiDung: "Tôi khó chịu khi việc làm qua loa" },
      { ma: "PH-C4", truc: "C", dao: false,
        noiDung: "Tôi muốn có số liệu rõ ràng rồi mới quyết" },
      { ma: "PH-C5", truc: "C", dao: false,
        noiDung: "Tôi lên kế hoạch trước cho các việc lớn" },
      { ma: "PH-C6", truc: "C", dao: true,
        noiDung: "Tôi quyết theo cảm giác nhiều hơn theo cân nhắc" },
    ],
  },
  QS: {
    ma: "QS",
    ten: "Bố mẹ nhìn con",
    aiTraLoi: "Phụ huynh",
    veAi: "Con 8–15 tuổi",
    loaiThang: "dong-y",
    mucToiDa: 5,
    cauMoiMan: 5,
    cauDan: "Chỉ trả lời theo những gì bạn THẬT SỰ nhìn thấy con làm, đừng đoán bụng con.",
    thang: [
      { giaTri: 1, nhan: "Rất không đúng với con tôi" },
      { giaTri: 2, nhan: "Không đúng lắm" },
      { giaTri: 3, nhan: "Nửa nọ nửa kia" },
      { giaTri: 4, nhan: "Khá đúng với con tôi" },
      { giaTri: 5, nhan: "Rất đúng với con tôi" },
    ],
    cau: [
      { ma: "QS-D1", truc: "D", dao: false, soiGuong: ["THCS-D1", "TH-D1"],
        noiDung: "Con tôi tự quyết rồi mới báo, hơn là hỏi ý trước" },
      { ma: "QS-D2", truc: "D", dao: false, soiGuong: ["THCS-D2", "TH-D2"],
        noiDung: "Con tôi nhận phần khó về mình" },
      { ma: "QS-D3", truc: "D", dao: false, soiGuong: ["THCS-D3", "TH-D3"],
        noiDung: "Con tôi nói thẳng khi thấy điều gì chưa đúng" },
      { ma: "QS-D4", truc: "D", dao: true, soiGuong: ["THCS-D6", "TH-D5"],
        noiDung: "Con tôi thường đợi người khác quyết rồi làm theo" },
      { ma: "QS-I1", truc: "I", dao: false, soiGuong: ["THCS-I2", "TH-I1"],
        noiDung: "Về đến nhà, con kể ngay chuyện xảy ra ở lớp" },
      { ma: "QS-I2", truc: "I", dao: false, soiGuong: ["THCS-I1", "TH-I2"],
        noiDung: "Con tôi làm quen với bạn mới rất nhanh" },
      { ma: "QS-I3", truc: "I", dao: false, soiGuong: ["THCS-I3", "TH-I3"],
        noiDung: "Con tôi thích trình bày, biểu diễn trước mọi người" },
      { ma: "QS-I4", truc: "I", dao: true, soiGuong: ["THCS-I6", "TH-I5"],
        noiDung: "Con tôi thích ở một mình sau khi đi chơi về" },
      { ma: "QS-S1", truc: "S", dao: false, soiGuong: ["THCS-S3", "TH-S2"],
        noiDung: "Con tôi nhường bạn để khỏi tranh cãi" },
      { ma: "QS-S2", truc: "S", dao: false, soiGuong: ["THCS-S4", "TH-S3"],
        noiDung: "Con tôi cần biết trước lịch thì mới yên tâm" },
      { ma: "QS-S3", truc: "S", dao: false, soiGuong: ["THCS-S5", "TH-S1"],
        noiDung: "Con tôi chờ được lâu mà không sốt ruột" },
      { ma: "QS-S4", truc: "S", dao: true, soiGuong: ["THCS-S6", "TH-S5"],
        noiDung: "Đổi lịch đột ngột không làm con tôi khó chịu" },
      { ma: "QS-C1", truc: "C", dao: false, soiGuong: ["THCS-C1", "TH-C2"],
        noiDung: "Con tôi soát lại bài trước khi nộp" },
      { ma: "QS-C2", truc: "C", dao: false, soiGuong: ["THCS-C4", "TH-C4"],
        noiDung: "Con tôi hỏi lại cho rõ trước khi bắt tay vào làm" },
      { ma: "QS-C3", truc: "C", dao: false, soiGuong: ["THCS-C3", "TH-C1"],
        noiDung: "Con tôi khó chịu khi đồ đạc lộn xộn" },
      { ma: "QS-C4", truc: "C", dao: true, soiGuong: ["THCS-C6", "TH-C5"],
        noiDung: "Con tôi làm trước rồi tính sau" },
    ],
  },
};
